### ISSUE TITLE
http://www.smallvictory.co/ not whitelisted for google OAuth: Error: redirect_uri_mismatch

### ISSUE THREAD

**Issue by despairblue** [chrischavarro/SmallVictory-JS#1]
Using the site from http://small-victory-mern.herokuapp.com/ works.

**Comment by chrischavarro** [comment]
Thanks for pointing that out! I’ve added the domain to the OAuth whitelist. Let me know if it works for you now.

**Comment by despairblue** [comment]
@chrischavarro works now 👍 

Thanks!
